tags:
  schema_web_page_type: CollectionPage
  schema_web_page_id: '[term:url]#collection'
  schema_web_page_description: '[term:description]'
  schema_web_page_in_language: '[term:langcode]'
  schema_web_page_is_accessible_for_free: 'True'
